security:
  # Gestion du hachage des mots de passe
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  # Définir les fournisseurs d'utilisateurs
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    # used to reload user from session & other features (e.g. switch_user)

  firewalls:
    # Désactiver la sécurité pour le profiler Symfony et les assets en dev
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # Endpoint pour l'authentification (login)
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # Firewall principal pour les endpoints protégés
    api:
      pattern: ^/api
      stateless: true
      jwt: ~ # Activer l'authentification par JWT

  # Contrôle d'accès
  access_control:
    # Accès public pour l'inscription et le login
    - { path: ^/api/register, roles: PUBLIC_ACCESS }
    - { path: ^/api/login, roles: PUBLIC_ACCESS }

    # Accès restreint pour tous les autres endpoints
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

# Configuration spécifique aux tests
when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Bcrypt : valeur minimale
        time_cost: 3 # Argon : valeur minimale
        memory_cost: 10 # Argon : valeur minimale
